export enum FunnelType {
  ULTRA_FAST_FUNNEL = "ULTRA_FAST_FUNNEL",
  ULTRA_FAST_WEBSITE = "ULTRA_FAST_WEBSITE",
  EASY_WEBSITES = "EASY_WEBSITES",
  SMART_WEBSITES = "SMART_WEBSITES",
  SIMPLE_WEBSITES = "SIMPLE_WEBSITES",
}
